### ISSUE TITLE
Default timeouts and connections per host for URL lengthener, page, site map, and robot rules fetchers

### ISSUE THREAD

**Issue by kkrugler** [ScaleUnlimited/flink-crawler#102]
When running test crawls on my machine, this is timing out, which kills the job.

I've bumped it to something much bigger, but the real solution is to figure out how to incorporate @vmagotra's work on supporting a max fetch duration in the actual fetcher code.

**Comment by kkrugler** [comment]
Actually the real problem is that the HttpClient being used for lengthening (a) isn't setting the `maxSimultaneousRequests`, so it's defaulting to 1, and (b) isn't setting `maxConnectionsPerHost`, so it's defaulting to 2. Since we're hitting (mostly) http://bit.ly, we need to have both of these set to `fetcherspertask` parameter for the job.

**Comment by Schmed** [comment]
There's also the issue of getting the these two attributes of the other BaseHttpFetcherBuilder objects (i.e., for pages, site maps, and robot rules) set appropriately (at least for CrawlTool, if not by default in CrawlTopologyBuilder). Currently, I think only the page fetcher gets its `maxSimultaneousRequests` set, and none of the three get their `maxConnectionsPerHost` set.

**Comment by Schmed** [comment]
Note that although FetchUrlsFunction for the page fetcher is constructed using `_pageFetcherBuilder.getFetchDurationTimeoutInSeconds() * 2`, the builder's instance field isn't being set up first.
