### ISSUE TITLE
Support separate QUEUED vs. FETCHING status

### ISSUE THREAD

**Issue by kkrugler** [ScaleUnlimited/flink-crawler#128]
When we pull a URL out of the fetch queue, we need to use a side output to update the state to FETCHING. This side output is a `CrawlStateUrl` that gets unioned in with other status updates (from robots check and fetch results).

**Comment by kkrugler** [comment]
@Schmed - is this now resolved?

**Comment by Schmed** [comment]
I think so, yes.
