### ISSUE TITLE
ParseFunction is not displayed in the execution graph 

### ISSUE THREAD

**Issue by vmagotra** [ScaleUnlimited/flink-crawler#131]
From Ken -

    I think this might be a bug...

        // Save off parsed page content by passing it on to the provided content sink function.
        parsedUrls
            .name("Select fetched content")
            .addSink(_contentSink)
            .name("ContentSink")
            .setParallelism(parseParallelism);

        // Save off parsed page content text. So just extract the parsed content text piece of the Tuple3, and
        // then pass it on to the provided content sink function (or just send it to the console).
        DataStream<String> contentText = parsedUrls
                .map(new MapFunction<ParsedUrl, String>() {

    The issue is that calling parsedUrls.blah() returns a (potentially new) stream, which we’re not using to update the parsedUrls variable.

    So then when we create the contentText stream, we’re using the old value for parsedUrls.

**Comment by kkrugler** [comment]
Hi @vmagotra - is this now resolved?

**Comment by vmagotra** [comment]
Yes, this can be closed.
