### ISSUE TITLE
Can't resolve dependency com.github.crawler-commons:http-fetcher:0.1-SNAPSHOT

### ISSUE THREAD

**Issue by IvanBiv** [ScaleUnlimited/flink-crawler#147]
In IntelliJ IDEA to try build project but dependency com.github.crawler-commons:http-fetcher:0.1-SNAPSHOT can't resolve but other is ok.
I use Master branch on commit "Refactored CrawlTool to pull out private methods to a new class Crawl… (#144)".
What is the reason?

**Comment by vmagotra** [comment]
Hi Ivan,
Did you build and install crawler-commons http-fetcher locally in your maven repo as per the instructions on https://github.com/ScaleUnlimited/flink-crawler/wiki/Build-Instructions ?

**Comment by IvanBiv** [comment]
@vmagotra thanks.
I didn't see this.
Now, I run step by step and crawler was build.
My recommendation:
```
git clone https://github.com/crawler-commons/http-fetcher.git
cd http-fetcher
mvn install 
```

@vmagotra, we build service with web crawler and I tried something tools and I am not very satisfied. And I see you project is growing.
Where I can ask you about some things? With create a new issue?

**Comment by Schmed** [comment]
I added the `cd http-fetcher` command you suggested to the [instructions](https://github.com/ScaleUnlimited/flink-crawler/wiki/Build-Instructions). OK to close this issue now?

**Comment by IvanBiv** [comment]
@kkrugler ok, thanks.
