### ISSUE TITLE
FetchStatus->Queued is decremented, but never incremented

### ISSUE THREAD

**Issue by Schmed** [ScaleUnlimited/flink-crawler#148]
We're currently getting the following output after running locally:

Accumulator Results: 
- FetchStatus->HTTP_NOT_FOUND (java.lang.Long): 1047
- FetchStatus->UNFETCHED (java.lang.Long): 10038
- FetchStatus->ABORTED_FETCH_SETTINGS (java.lang.Long): 10
- FetchStatus->FETCHING (java.lang.Long): 2099
- FetchStatus->QUEUED (java.lang.Long): -1991
- FetchStatus->FETCHED (java.lang.Long): 826

This is because the decrement of FetchStatus->QUEUED has no matching increment. All of the manipulations of the FetchStatus counters should be reviewed.

**Comment by kkrugler** [comment]
Hi @Schmed - I think you fixed this already

**Comment by Schmed** [comment]
This was indeed resolved by pull request #150

**Comment by Schmed** [comment]
This was indeed resolved by pull request #150
