### ISSUE TITLE
Add CrawlPolicy support to control termination, etc.

### ISSUE THREAD

**Issue by Schmed** [ScaleUnlimited/flink-crawler#28]
We could add multiple CrawlPolicy objects, but by default we'd have a StopFileCrawlPolicy that would look for a stop file somewhere (in some kind of working dir in S3?) If any of these objects met its criteria, the CrawlDBFunction would stop putting URLs onto the fetch list, but would continue running until everything on the fetch list finished getting fetched and parsed, and we'd collected all of the outbound link URLs. Other CrawlPolicy objects might include MaxFetchedURLsCrawlPolicy, MaxCrawlTimeCrawlPolicy, etc.

**Comment by kkrugler** [comment]
The `SeedUrlSource and` `UrlDbFunction` now both take a terminating function, which can be used to cleanly shut down the flow. We have a `DurationCrawlTerminator` that's time-based. We don't yet have an implementation that looks for a stop file (in S3, typically), but we can file a separate issue for that when we need it.
