### ISSUE TITLE
Finish S3Utils support

### ISSUE THREAD

**Issue by Schmed** [ScaleUnlimited/flink-crawler#31]
Ken wrote a very basic S3Utils, but its fileExists method isn't even implemented (because the object doesn't yet have access to the S3 credentials). SeedUrlsSource is using the AmazonS3 client for reading from an S3-based seed URLs file (and it expects the credentials to be provided via [environment variables](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/EnvironmentVariableCredentialsProvider.html)), but there's probably some refactoring required here.

**Comment by kkrugler** [comment]
@Schmed - I'm going to re-assign this to you, as I think that Flink 1.4 could maybe fix the issue you ran into.
