### ISSUE TITLE
Support integration tests

### ISSUE THREAD

**Issue by kkrugler** [ScaleUnlimited/flink-crawler#59]
I've moved the `CommonCrawlFetcher` test code into `src/it/java/`, and tried to modify `pom.xml` so that this directory is added to the list of sources in the Eclipse project file, but it's not working yet.

**Comment by Schmed** [comment]
Shouldn't you the delete 59_support-it-tests branch now, @vmagotra ?

**Comment by vmagotra** [comment]
Thanks - I have deleted it.
