### ISSUE TITLE
Add more Flink metrics

### ISSUE THREAD

**Issue by kkrugler** [ScaleUnlimited/flink-crawler#74]
Now that we have metrics, we'd like to record some additional counters in `UrlDBFunction`
    * Number of active URLs (this is a gauge, value from `_activeUrls`)
    * URLs by status (might already be there now?)

Since we can't use metrics with async functions, just do logging in `CheckUrlWithRobotsFunction`
    * Number of missing robots.txt files
    * Number of fetched robots.txt files
    * Number of failed robots.txt files (other issues)

We only want to log when we are processing a new domain. So we'd output that domain, the result, and the current counter values for missing/fetched/failed.

**Comment by vmagotra** [comment]
Done.
