### ISSUE TITLE
Update CrawlTool to always require a user agent name and webpage

### ISSUE THREAD

**Issue by vmagotra** [ScaleUnlimited/flink-crawler#86]
Remove the default UserAgent settings from the CrawlTool so that a user is required to provide the agent name, web address and email address.

**Comment by Schmed** [comment]
Although this isn't required for the Flink Forward talk, I feel like I should take this on. I did some initial work in this area, and @vmagotra is on vacation this week.

**Comment by Schmed** [comment]
I handled this via https://github.com/ScaleUnlimited/flink-crawler/commit/0efd2e71ced07e0fc4c3aac80338005fd75d586b#diff-2a070fbbece0a7e69b81a5240a997585
