### ISSUE TITLE
Switch to using SideOutput versus splitting the stream

### ISSUE THREAD

**Issue by kkrugler** [ScaleUnlimited/flink-crawler#89]
See [side output](https://ci.apache.org/projects/flink/flink-docs-release-1.4/dev/stream/side_output.html) documentation. This would require using a [ProcessFunction](https://ci.apache.org/projects/flink/flink-docs-release-1.4/dev/stream/operators/process_function.html) or CoProcessFunction instead of a (Rich)(Co)(Flat)Map in various places.

**Comment by kkrugler** [comment]
This might cause problems with our code that generates a .dot file, as there's a [bug reported](https://issues.apache.org/jira/browse/FLINK-8498) in Flink 1.4 about `getExecutionPlan()` failing when the graph uses side outputs.

**Comment by Schmed** [comment]
I'm going to take a whack at this one, Vivek
